config/routes.rb
Rails.application.routes.draw do
  root 'rsvps#show'
  resources :rsvps

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base

  validates :name, presence: true
  validates :attending, presence: true

  def attending?
    attending == 'yay'
  end

  def name_message
    if attending?
      'WHO IS JAMMING?'
    else
      "WHO CAN'T JAM?"
    end
  end

  def comment_message
    'THOUGHTS, WELL WISHES TO SHARE WITH CPBG?'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController

  def show
    @already_rsvpd = cookies[:cpbg_rsvp]
  end

  def index
    @rsvps = Rsvp.all
  end

  def new
    @rsvp = Rsvp.new(attending: params[:rsvp])
  end

  def create
    @rsvp = Rsvp.new(rsvp_params)
    @rsvp.save if @rsvp.valid?
  end

 private

  def rsvp_params
    params.require(:rsvp).permit(:name, :comment, :attending)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jamboree</title>
  <%= stylesheet_link_tag    'reset', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//use.typekit.net/kdo0xdm.js"></script>
  <script>try{Typekit.load({ async: true });}catch(e){}</script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rsvps/_new.html.haml
= form_for @rsvp, remote: true, html: {class: @rsvp.attending} do |f|
  .inputs
    = f.hidden_field :attending, value: @rsvp.attending
    = f.label :name, @rsvp.name_message
    = f.text_field :name
    = f.label :comment, @rsvp.comment_message
    = f.text_area :comment, cols: 87, rows: 4
    .submit
      = f.submit 'SEND'

  #cancel
    X

app/views/rsvps/index.html.haml
%table.rsvps
  %tr
    %th.attending Attending
    %th.name Name
    %th.comment Comment
    %th.date Date

  - @rsvps.each do |rsvp|
    %tr{class: cycle('even', 'odd')}
      %td= rsvp.attending
      %td= rsvp.name
      %td= rsvp.comment
      %td= rsvp.created_at

app/views/rsvps/show.html.haml
#top-bar
  - if @already_rsvpd
    %h1 THANKS FOR HOLLERING!
  - else
    %h1 WILL YOU JAM WITH US?
    #vote
      = link_to 'YAY', new_rsvp_path(rsvp: 'yay'), :remote => true, :id => 'yay'
      = link_to 'NAY', new_rsvp_path(rsvp: 'nay'), :remote => true, :id => 'nay'

  #ribbon
    = image_tag 'CPBG_Logo.png'

#form

#hero
  = image_tag 'CPBG_Jam.png', :class => 'full'

.content
  = image_tag 'CPBG_Date.png', :class => 'full'

  %p
    We’ll start around 4pm and keep going until we are done. Come by when you can; stay as late as you like. We’ll be grilling half smokes and veggie half smokes; chomping on potato chips; scooping up salads; filling pints with homemade beer; ogling at the fall foliage; and celebrating all things Craig and Becca.

  .spacer &nbsp;

  #midline
    %h2
      CABOOSE FARM
      %span.ornament= image_tag("CPBG_ornament.png")
      SABILLASVILLE, MD

  .spacer &nbsp;

  %h3 14754 MANAHAN RD, SABILLASVILLE, MD 21780

  %p
    Trees! A pond! Farm houses named after presidents! A real train caboose! A perfect dose of adventure for our little, informal to-do. To get there: take I-270 to US-15 N in Frederick; Stay on 15 until MD-77 and exit toward Thurmont; Turn right onto MD-77 W (W Main St); Right onto Foxville Deerfield Rd and continue straight onto Manahan Rd. On your left you’ll see a barn (there should be a Caboose Farm sign). Park in the gravel parking lot by the barn, walk across the street, past the pond, past the caboose and on to the Jefferson House for the fun.

  %p
    The Jamboree is a casual, family affair and the best gift is spending time with y'all!  No gifts, please.

#bottom-spacer
#bottom-bar
  .left
    = image_tag 'CPBG_LogoHrz.png'

    %p
      In May 2012, the partnership between Craig Partin and Becca Gurney formed over skeeball and pie. They’ve been on adventure since. The partnership was made legal at a private, civil ceremony in Fall 2015.

  .right
    = image_tag 'CPBG_cpbg.png'